export * as Header  from './components/header'
export * as Footer  from './components/footer'
export * as Faq  from './components/faq'
export * as Feature  from './components/feature'
export * as CallToAction  from './components/callToAction'